Added Webhook support
thisdavej/ngrok-notify pull request #6
Opened 2019-08-21 23:19 UTC by polloss

Added support to call a webhook and send ngrok url
Changed default behavior for email, now email is not sent by default unless the -e, --email param is specified

2019-08-27 16:21 UTC, thisdavej requested changes
Excellent work!  I love the addition of webhooks and other changes you have added.  If you could address my minor comments/suggestions, I will merge. Thanks!

2019-08-27 16:21 UTC, thisdavej commented on cli.js
>      Create ngrok tunnel to expose localhost web server running on port 8080.
Update these examples to reflect the new "-e" optional argument since we will no longer be using "-n". This is important since these examples will appear when using command-line help.

2019-08-27 16:21 UTC, thisdavej commented on config.yml
> +  url: https://example.com/myngrockhook
minor edit recommended: change URL to be https://example.com/myngrokhook so "ngrok" is spelled correctly.

2019-08-29 16:37 UTC, jd-aguilera commented on cli.js
>      Create ngrok tunnel to expose localhost web server running on port 8080.
Right, I missed this part. Changes are in the branch now :)

2019-08-29 16:39 UTC, polloss commented
Your suggestions are up now! It should be ready to be merged

2019-08-30 15:16 UTC, thisdavej approved these changes

2019-08-30 15:17 UTC, merged

2019-08-30 15:18 UTC, thisdavej commented
Excellent work @polloss.  Thanks for contributing valuable code to ngrok-notify!